export const theme = {
  colors: {
    background: '#FAF9F6',
    primary: '#AB003E',
    primaryPressed: '#970037',
    text: '#2C2C2C',
    title: '#101010',
    label: '#3B3B3B',
    titleZyra: '#000000',
    muted: '#4D4D4D',
    muted2: '#5F5F5F',
    input: '#E1E1E1',
    inputText: '#464646',
    white: '#FFFFFF',
    border: '#D4D4D4',
    link: '#B90043',
    shadow: '#DE0051',
    cinzaClaro: '#CCCCCC',
  },
  spacing: {
    screen: 20,
  },
  radius: {
    input: 10,
    button: 10,
  },
  fonts: {
    regular: 'PoppinsRegular',
    medium: 'PoppinsMedium',
    semiBold: 'PoppinsSemiBold',
    bold: 'PoppinsBold',
    extraBold: 'PoppinsExtraBold',
    black: 'PoppinsBlack',
    title: 'Jomhuria',
  },
} as const;
